CREATE DATABASE EMS;

--Designation Table
CREATE TABLE Designation(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE()
);

-- Department Table
CREATE TABLE Department(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE()

);

--Employee Table
CREATE TABLE Employee(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(15),
	Address NVARCHAR(255),
	DOB DATE,
	DesignationId INT NOT NULL,
	DepartmentId INT NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME DEFAULT GETDATE(),
	CONSTRAINT FK_Employee_Designation FOREIGN KEY(DesignationId) REFERENCES Designation(Id),
	CONSTRAINT FK_Employee_Department FOREIGN KEY(DepartmentId) REFERENCES Department(Id),
);
